# https://travis-ci.org

language: cpp

install:
  - sudo apt-get install -qq libboost-all-dev

script:
  - cd any && make && cd ..
  - cd function && make && cd ..
  - cd make_shared && make && cd ..
  - cd property_tree && make && cd ..
  - cd smart_pointer && make && cd ..
  - cd thread && make && cd ..
